project_id = "aiffhgbzoxglfewdutea"

[functions.check-auto-close]
verify_jwt = false

[functions.tirage-sort]
verify_jwt = false

[functions.evaluate-bet]
verify_jwt = false

[functions.flag-gazette-message]
verify_jwt = false

[functions.km-vote]
verify_jwt = false

[functions.activate-proposal]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.admin-notify-email]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.nuclear-reset]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false
